services:
  fideb-ui:
    build: .
    container_name: fideb-ui
    ports:
      - "80:80"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - PORT=80
    restart: unless-stopped
